//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.SceneManagement;

public class CStateHome: CState
{
	private HomeController m_controller;

	public override void Enter(UnityEngine.GameObject entity)
	{
		SceneManager.LoadScene ("home", LoadSceneMode.Single);
        Resources.UnloadUnusedAssets();
		GUIManager.getInstance ().getHomeController ().Show ();
	}
	
	public override void Execute(UnityEngine.GameObject entity)
	{

	}
	
	public override void Exit(UnityEngine.GameObject entity)
	{
		GUIManager.getInstance ().getHomeController ().Hide ();
	}
}

