//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.SceneManagement;

public class CStateInit : CState
{

    public override void Enter(UnityEngine.GameObject entity)
    {
		Bootstrap.StateMachine.ChangeState (Bootstrap.State.Home);
		
    }

    public override void Execute(UnityEngine.GameObject entity)
    {

    }

    public override void Exit(UnityEngine.GameObject entity)
    {

    }

	private void BindUIActions()
	{
		
	}

	private void RemoveUIAction()
	{
		
	}

	private void OnNewGame()
	{
		
	}

	private void OnResume()
	{
		
	}

	private void OnOption()
	{
	}
}

