//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public abstract class GameStateBase: GameState
{
	protected Game m_Game;

	public override void Enter(UnityEngine.GameObject entity)
	{
		this.m_Game = entity.GetComponent<Game>();
	}
}
